# Generated by Django 5.2.17 on 2026-08-19 15:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=80)),
                ('entity_type', models.CharField(max_length=120)),
                ('entity_id', models.CharField(blank=True, max_length=120)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('before_values', models.JSONField(blank=True, default=dict)),
                ('after_values', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-occurred_at',),
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='audit_audit_entity__0bff9a_idx'), models.Index(fields=['action', 'occurred_at'], name='audit_audit_action_7e10a4_idx')],
            },
        ),
    ]
