# Generated by Django 5.2.17 on 2026-08-19 16:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=160, unique=True),
        ),
        migrations.CreateModel(
            name='SKUValueHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_at', models.DateTimeField(auto_now_add=True)),
                ('retail_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('master_cogs', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('source_batch_id', models.UUIDField()),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sku_value_changes', to=settings.AUTH_USER_MODEL)),
                ('product_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.productstatus')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='value_history', to='master_data.sku')),
            ],
            options={
                'ordering': ('-effective_at',),
                'indexes': [models.Index(fields=['sku', 'effective_at'], name='master_data_sku_id_a2ce18_idx')],
            },
        ),
    ]
