# Generated by Django 5.2.17 on 2026-08-19 18:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_alter_product_code_skuvaluehistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceSKUMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('Shopee', 'Shopee'), ('Tiktok', 'TikTok')], max_length=20)),
                ('marketplace_sku_id', models.CharField(max_length=180)),
                ('marketplace_seller_sku', models.CharField(blank=True, max_length=180)),
                ('product_name_evidence', models.CharField(blank=True, max_length=255)),
                ('variation_evidence', models.CharField(blank=True, max_length=120)),
                ('evidence_reference', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_sku_mappings', to='master_data.sku')),
            ],
            options={
                'ordering': ('source', 'marketplace_sku_id'),
                'constraints': [models.UniqueConstraint(fields=('source', 'marketplace_sku_id'), name='master_unique_marketplace_sku_mapping')],
            },
        ),
    ]
