# Generated by Django 5.2.17 on 2026-09-09 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_access_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tab_access',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
