# Generated by Django 5.2.17 on 2026-08-19 17:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('as_of_date', models.DateField()),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('PASSED', 'Passed'), ('FAILED', 'Failed')], default='RUNNING', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('totals', models.JSONField(blank=True, default=dict)),
                ('check_summary', models.JSONField(blank=True, default=dict)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='ReconciliationIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('WARNING', 'Warning')], max_length=20)),
                ('code', models.CharField(max_length=80)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_key', models.CharField(max_length=240)),
                ('expected_value', models.CharField(blank=True, max_length=200)),
                ('actual_value', models.CharField(blank=True, max_length=200)),
                ('difference', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='reconciliation.reconciliationrun')),
            ],
            options={
                'ordering': ('severity', 'code', 'entity_key'),
            },
        ),
    ]
