# Generated by Django 5.2.17 on 2026-09-01 08:43

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('objective', models.TextField(blank=True)),
                ('target_launch_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('DEVELOPMENT', 'Development'), ('MARKETING_REVIEW', 'Marketing Review'), ('COMMERCIAL_APPROVED', 'Commercial Approved')], default='DRAFT', max_length=30)),
                ('handed_over_at', models.DateTimeField(blank=True, null=True)),
                ('commercial_approved_at', models.DateTimeField(blank=True, null=True)),
                ('commercial_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rnd_collections_commercially_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rnd_collections_created', to=settings.AUTH_USER_MODEL)),
                ('handed_over_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rnd_collections_handed_over', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DevelopmentProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('working_code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=180)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('product_story', models.TextField(blank=True)),
                ('target_customer', models.TextField(blank=True)),
                ('target_retail_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_cogs', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('final_sample_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('CONCEPT', 'Concept'), ('SAMPLING', 'Sampling'), ('REVISION', 'Revision'), ('COSTING', 'Costing'), ('FINAL_APPROVED', 'Final R&D')], default='CONCEPT', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('rnd_approved_at', models.DateTimeField(blank=True, null=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='rnd.collection')),
                ('rnd_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rnd_products_approved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='MarketingRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommendation', models.CharField(choices=[('GO', 'GO'), ('REVISE', 'Revise'), ('HOLD', 'Hold'), ('DROP', 'Drop')], max_length=20)),
                ('recommended_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('rationale', models.TextField()),
                ('recommended_at', models.DateTimeField()),
                ('official_decision', models.CharField(blank=True, choices=[('GO', 'GO'), ('REVISE', 'Revise'), ('HOLD', 'Hold'), ('DROP', 'Drop')], max_length=20)),
                ('official_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('official_note', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rnd_official_decisions', to=settings.AUTH_USER_MODEL)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='marketing_recommendation', to='rnd.developmentproduct')),
                ('recommended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rnd_marketing_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('product__created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='developmentproduct',
            constraint=models.UniqueConstraint(fields=('collection', 'working_code'), name='rnd_unique_working_code_per_collection'),
        ),
        migrations.AddConstraint(
            model_name='marketingrecommendation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('recommendation', 'GO'), ('recommended_quantity__gt', 0)), models.Q(models.Q(('recommendation', 'GO'), _negated=True), ('recommended_quantity__isnull', True)), _connector='OR'), name='rnd_recommendation_go_quantity_rule'),
        ),
        migrations.AddConstraint(
            model_name='marketingrecommendation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('official_decision', ''), ('official_quantity__isnull', True)), models.Q(('official_decision', 'GO'), ('official_quantity__gt', 0)), models.Q(models.Q(('official_decision__in', ('', 'GO')), _negated=True), ('official_quantity__isnull', True)), _connector='OR'), name='rnd_official_go_quantity_rule'),
        ),
    ]
