# Generated by Django 5.2.17 on 2026-09-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developmentproduct',
            name='bill_of_material',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='developmentproduct',
            name='mockup',
            field=models.FileField(blank=True, upload_to='rnd/mockups/'),
        ),
        migrations.AddField(
            model_name='developmentproduct',
            name='technical_drawing',
            field=models.FileField(blank=True, upload_to='rnd/technical_drawings/'),
        ),
    ]
