# Generated by Django 5.2.17 on 2026-09-01 09:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnd', '0002_developmentproduct_bill_of_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developmentproduct',
            name='bill_of_material',
        ),
        migrations.CreateModel(
            name='DevelopmentProductMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.CharField(max_length=180)),
                ('requirement', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0001)])),
                ('eom', models.CharField(max_length=40)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='rnd.developmentproduct')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
