# Generated by Django 5.2.17 on 2026-09-02 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnd', '0003_remove_developmentproduct_bill_of_material_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='developmentproduct',
            name='approved_document',
            field=models.FileField(blank=True, upload_to='rnd/approved_documents/'),
        ),
        migrations.AddField(
            model_name='developmentproduct',
            name='document_revision',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='developmentproduct',
            name='document_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Menunggu Approval'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='developmentproduct',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='developmentproduct',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rnd_products_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='developmentproduct',
            name='submitted_document',
            field=models.FileField(blank=True, upload_to='rnd/submitted_documents/'),
        ),
    ]
