# Generated by Django 5.2.17 on 2026-09-03 06:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_document_revisions(apps, schema_editor):
    DevelopmentProduct = apps.get_model('rnd', 'DevelopmentProduct')
    DocumentRevision = apps.get_model('rnd', 'DevelopmentProductDocumentRevision')
    products = DevelopmentProduct.objects.filter(
        document_status__in=('SUBMITTED', 'APPROVED'),
        submitted_at__isnull=False,
    ).exclude(submitted_document='')
    for product in products.iterator():
        revision = DocumentRevision(
            product_id=product.id,
            revision=product.document_revision,
            status=product.document_status,
            submitted_at=product.submitted_at,
            submitted_by_id=product.submitted_by_id,
            approved_at=product.rnd_approved_at,
            approved_by_id=product.rnd_approved_by_id,
        )
        revision.submitted_document = product.submitted_document
        revision.approved_document = product.approved_document
        revision.save()


class Migration(migrations.Migration):

    dependencies = [
        ('rnd', '0004_developmentproduct_approved_document_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='developmentproduct',
            name='document_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Menunggu Approval'), ('APPROVED', 'Approved'), ('REVISION_REQUESTED', 'Revisi Diminta')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='DevelopmentProductDocumentRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('SUBMITTED', 'Menunggu Approval'), ('APPROVED', 'Approved'), ('REVISION_REQUESTED', 'Revisi Diminta')], max_length=20)),
                ('submitted_document', models.FileField(upload_to='rnd/document_revisions/submitted/')),
                ('approved_document', models.FileField(blank=True, upload_to='rnd/document_revisions/approved/')),
                ('submitted_at', models.DateTimeField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('revision_requested_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rnd_document_revisions_approved', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_revisions', to='rnd.developmentproduct')),
                ('revision_requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rnd_document_revisions_requested', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rnd_document_revisions_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('revision',),
                'constraints': [models.UniqueConstraint(fields=('product', 'revision'), name='rnd_unique_document_revision_per_product')],
            },
        ),
        migrations.RunPython(backfill_document_revisions, migrations.RunPython.noop),
    ]
