# Generated by Django 5.2.17 on 2026-09-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnd', '0005_alter_developmentproduct_document_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developmentproductdocumentrevision',
            name='revision_note',
            field=models.TextField(blank=True),
        ),
    ]
