# Generated by Django 5.2.17 on 2026-09-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnd', '0006_developmentproductdocumentrevision_revision_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='developmentproduct',
            name='product_cover',
            field=models.FileField(blank=True, upload_to='rnd/product_covers/'),
        ),
    ]
