# Generated by Django 5.2.17 on 2026-09-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnd', '0007_developmentproduct_product_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='developmentproductdocumentrevision',
            name='revision_target',
            field=models.CharField(blank=True, choices=[('MOCKUP', 'MDR / Mockup'), ('TECHNICAL_DRAWING', 'Technical Drawing'), ('BOTH', 'MDR / Mockup dan Technical Drawing')], max_length=30),
        ),
    ]
