# Generated by Django 5.2.17 on 2026-09-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnd', '0013_collection_marketing_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developmentproduct',
            name='document_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Menunggu Approval'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved'), ('REVISION_REQUESTED', 'Revisi Diminta')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='developmentproductdocumentrevision',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Menunggu Approval'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved'), ('REVISION_REQUESTED', 'Revisi Diminta')], max_length=20),
        ),
    ]
