# Generated by Django 5.2.17 on 2026-09-16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rnd", "0014_alter_developmentproduct_document_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DevelopmentProductStageDate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stage_key", models.CharField(max_length=80)),
                ("target_date", models.DateField(blank=True, null=True)),
                ("actual_date", models.DateField(blank=True, null=True)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="stage_dates", to="rnd.developmentproduct")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="rnd_development_stage_dates_updated", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ("created_at",),
                "constraints": [models.UniqueConstraint(fields=("product", "stage_key"), name="rnd_unique_stage_date_per_product")],
            },
        ),
    ]
