# Generated by Django 5.2.17 on 2026-09-23 07:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_product_sales_account'),
        ('sales', '0012_salesorderline_current_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesJournalAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gross_sales', models.DecimalField(decimal_places=6, max_digits=22)),
                ('net_sales', models.DecimalField(decimal_places=6, max_digits=22)),
                ('cogs', models.DecimalField(decimal_places=6, max_digits=22)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_allocations', to='finance.journalentry')),
                ('sales_line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='finance_journal_allocation', to='sales.salesorderline')),
            ],
            options={
                'ordering': ('entry__entry_date', 'sales_line__order__order_number'),
            },
        ),
    ]
