# Generated by Django 5.2.17 on 2026-09-24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_salesjournalallocation"),
        ("inventory", "0017_reset_active_po_wip_before_qc"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesReturnJournalAllocation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("return_amount", models.DecimalField(decimal_places=6, max_digits=22)),
                ("reversed_cogs", models.DecimalField(decimal_places=6, max_digits=22)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("entry", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="sales_return_allocations", to="finance.journalentry")),
                ("return_receipt", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="finance_journal_allocation", to="inventory.physicalreturnreceipt")),
            ],
            options={
                "ordering": ("entry__entry_date", "return_receipt__received_date"),
            },
        ),
    ]
