# Generated by Django 5.2.17 on 2026-08-19 17:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0002_alter_product_code_skuvaluehistory'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FIFOAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allocated_qty', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=18)),
                ('allocated_cost', models.DecimalField(decimal_places=4, max_digits=20)),
                ('returned_qty', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
            ],
            options={
                'ordering': ('outbound_movement', 'layer__receipt_date', 'layer__created_at'),
            },
        ),
        migrations.CreateModel(
            name='InboundReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inbound_date', models.DateField()),
                ('received_qty', models.DecimalField(decimal_places=4, max_digits=18)),
                ('reference', models.CharField(max_length=120, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('inbound_date', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='InventoryException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('NEGATIVE_OPENING', 'Negative Opening'), ('FIFO_SHORT_QTY', 'FIFO Short Qty'), ('RETURN_SOURCE_MISSING', 'Return Source Missing'), ('INVALID_ADJUSTMENT', 'Invalid Adjustment')], max_length=40)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_reason', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('status', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_key', models.CharField(max_length=240, unique=True)),
                ('movement_date', models.DateField()),
                ('movement_type', models.CharField(choices=[('OPENING', 'Opening'), ('INCOMING', 'Incoming'), ('SALES_OUT', 'Sales Out'), ('RETURN_IN', 'Return In'), ('ADJUSTMENT_IN', 'Adjustment In'), ('ADJUSTMENT_OUT', 'Adjustment Out')], max_length=30)),
                ('direction', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], max_length=3)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('allocated_cost', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('source_reference', models.CharField(max_length=200)),
                ('reason', models.TextField(blank=True)),
                ('evidence_reference', models.CharField(blank=True, max_length=240)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('movement_date', 'movement_type', 'sku__sku', 'movement_key'),
            },
        ),
        migrations.CreateModel(
            name='PhysicalReturnReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('received_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('condition', models.CharField(choices=[('SELLABLE', 'Sellable'), ('DAMAGED', 'Damaged'), ('DEFECTIVE', 'Defective'), ('MISSING_LOST', 'Missing/Lost'), ('WRONG_ITEM', 'Wrong Item'), ('WAITING_INSPECTION', 'Waiting Inspection')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('received_date', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='QCInspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inspected_at', models.DateTimeField()),
                ('qty_inspected', models.DecimalField(decimal_places=4, max_digits=18)),
                ('qty_passed', models.DecimalField(decimal_places=4, max_digits=18)),
                ('qty_failed', models.DecimalField(decimal_places=4, max_digits=18)),
                ('failed_disposition', models.CharField(blank=True, choices=[('WAITING_DECISION', 'Waiting Decision'), ('REWORK', 'Rework'), ('REPLACEMENT_REQUESTED', 'Replacement Requested'), ('REJECTED', 'Rejected'), ('ACCEPTED_WITH_EXCEPTION', 'Accepted with Exception')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('inspected_at', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='ExpectedReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expected_qty', models.DecimalField(decimal_places=4, max_digits=18)),
                ('status', models.CharField(choices=[('EXPECTED', 'Expected'), ('PARTIALLY_RECEIVED', 'Partially Received'), ('RECEIVED', 'Received')], default='EXPECTED', max_length=30)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('sales_line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='expected_return', to='sales.salesorderline')),
            ],
        ),
        migrations.CreateModel(
            name='FIFOLayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('layer_key', models.CharField(max_length=240, unique=True)),
                ('source_type', models.CharField(choices=[('OPENING', 'Opening'), ('PURCHASE_ORDER', 'Purchase Order')], max_length=30)),
                ('source_reference', models.CharField(max_length=200)),
                ('receipt_date', models.DateField()),
                ('original_qty', models.DecimalField(decimal_places=4, max_digits=18)),
                ('remaining_qty', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fifo_layers', to='master_data.sku')),
            ],
            options={
                'ordering': ('receipt_date', 'created_at', 'layer_key'),
            },
        ),
    ]
