# Generated by Django 5.2.17 on 2026-08-19 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('master_data', '0002_alter_product_code_skuvaluehistory'),
        ('purchasing', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fifolayer',
            name='source_po_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fifo_layers', to='purchasing.purchaseorderline'),
        ),
        migrations.AddField(
            model_name='fifoallocation',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='inventory.fifolayer'),
        ),
        migrations.AddField(
            model_name='inboundreceipt',
            name='po_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbound_receipts', to='purchasing.purchaseorderline'),
        ),
        migrations.AddField(
            model_name='inboundreceipt',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inboundreceipt',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbound_receipts', to='master_data.warehouse'),
        ),
        migrations.AddField(
            model_name='inventoryexception',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryexception',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_exceptions', to='master_data.sku'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='inbound_receipt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movement', to='inventory.inboundreceipt'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='sales_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='sales.salesorderline'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='master_data.sku'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='master_data.warehouse'),
        ),
        migrations.AddField(
            model_name='inventoryexception',
            name='movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exceptions', to='inventory.inventorymovement'),
        ),
        migrations.AddField(
            model_name='fifolayer',
            name='opening_movement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_fifo_layer', to='inventory.inventorymovement'),
        ),
        migrations.AddField(
            model_name='fifoallocation',
            name='outbound_movement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fifo_allocations', to='inventory.inventorymovement'),
        ),
        migrations.AddField(
            model_name='physicalreturnreceipt',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='physicalreturnreceipt',
            name='sales_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='physical_returns', to='sales.salesorderline'),
        ),
        migrations.AddField(
            model_name='physicalreturnreceipt',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='physical_returns', to='master_data.warehouse'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='return_receipt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movement', to='inventory.physicalreturnreceipt'),
        ),
        migrations.AddField(
            model_name='qcinspection',
            name='po_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_inspections', to='purchasing.purchaseorderline'),
        ),
        migrations.AddField(
            model_name='qcinspection',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='inboundreceipt',
            constraint=models.CheckConstraint(condition=models.Q(('received_qty__gt', 0)), name='inventory_inbound_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='fifolayer',
            constraint=models.CheckConstraint(condition=models.Q(('original_qty__gt', 0)), name='inventory_fifo_original_positive'),
        ),
        migrations.AddConstraint(
            model_name='fifolayer',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_qty__gte', 0)), name='inventory_fifo_remaining_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='fifolayer',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='inventory_fifo_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='fifoallocation',
            constraint=models.UniqueConstraint(fields=('outbound_movement', 'layer'), name='inventory_unique_movement_layer_allocation'),
        ),
        migrations.AddConstraint(
            model_name='fifoallocation',
            constraint=models.CheckConstraint(condition=models.Q(('allocated_qty__gt', 0)), name='inventory_allocation_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='fifoallocation',
            constraint=models.CheckConstraint(condition=models.Q(('returned_qty__gte', 0)), name='inventory_allocation_returned_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='physicalreturnreceipt',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='inventory_return_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='inventory_movement_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='qcinspection',
            constraint=models.CheckConstraint(condition=models.Q(('qty_inspected__gt', 0)), name='inventory_qc_inspected_positive'),
        ),
        migrations.AddConstraint(
            model_name='qcinspection',
            constraint=models.CheckConstraint(condition=models.Q(('qty_passed__gte', 0)), name='inventory_qc_passed_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='qcinspection',
            constraint=models.CheckConstraint(condition=models.Q(('qty_failed__gte', 0)), name='inventory_qc_failed_nonnegative'),
        ),
    ]
