# Generated by Django 5.2.17 on 2026-08-19 17:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        ('master_data', '0002_alter_product_code_skuvaluehistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryexception',
            name='resolution_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_exceptions', to='inventory.inventorymovement'),
        ),
        migrations.AlterField(
            model_name='fifolayer',
            name='source_type',
            field=models.CharField(choices=[('OPENING', 'Opening'), ('PURCHASE_ORDER', 'Purchase Order'), ('ADJUSTMENT', 'Approved Adjustment')], max_length=30),
        ),
        migrations.CreateModel(
            name='FIFOOpeningSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cutover_date', models.DateField()),
                ('opening_qty', models.DecimalField(decimal_places=4, max_digits=18)),
                ('frozen_unit_cogs', models.DecimalField(decimal_places=4, max_digits=18)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sku', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fifo_opening_snapshot', to='master_data.sku')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('frozen_unit_cogs__gte', 0)), name='inventory_opening_cogs_nonnegative')],
            },
        ),
    ]
