# Generated by Django 5.2.17 on 2026-08-19 18:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0004_alter_rawfile_dataset_type'),
        ('inventory', '0003_inventoryexception_resolution_movement_and_more'),
        ('master_data', '0002_alter_product_code_skuvaluehistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FIFOOpeningImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parser_version', models.CharField(default='fifo-opening-v1', max_length=30)),
                ('status', models.CharField(choices=[('PARSING', 'Parsing'), ('READY', 'Ready for approval'), ('BLOCKED', 'Blocked'), ('COMMITTED', 'Committed')], default='PARSING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('previewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('ready_rows', models.PositiveIntegerField(default=0)),
                ('blocking_issue_count', models.PositiveIntegerField(default=0)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('quality_summary', models.JSONField(blank=True, default=dict)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('raw_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fifo_opening_batches', to='imports.rawfile')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StagedFIFOOpeningRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.PositiveIntegerField()),
                ('sku_text', models.CharField(max_length=100)),
                ('opening_qty', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('frozen_unit_cogs', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('cutover_date', models.DateField(blank=True, null=True)),
                ('source_layer_key', models.CharField(blank=True, max_length=240)),
                ('proposed_action', models.CharField(choices=[('NEW', 'New'), ('BLOCKED', 'Blocked')], default='NEW', max_length=20)),
                ('original_data', models.JSONField(default=dict)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staged_rows', to='inventory.fifoopeningimportbatch')),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.sku')),
            ],
            options={
                'ordering': ('row_number',),
            },
        ),
        migrations.CreateModel(
            name='FIFOOpeningImportIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('ERROR', 'Error'), ('WARNING', 'Warning')], max_length=10)),
                ('code', models.CharField(max_length=80)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField()),
                ('is_blocking', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='inventory.fifoopeningimportbatch')),
                ('staged_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='inventory.stagedfifoopeningrow')),
            ],
            options={
                'ordering': ('-is_blocking', 'staged_row__row_number', 'code'),
            },
        ),
        migrations.AddConstraint(
            model_name='stagedfifoopeningrow',
            constraint=models.UniqueConstraint(fields=('batch', 'row_number'), name='inventory_unique_opening_batch_row'),
        ),
    ]
