# Generated by Django 5.2.17 on 2026-08-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_fifoopeningimportbatch_stagedfifoopeningrow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundreceipt',
            name='retail_price_snapshot',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
    ]
