# Generated by Django 5.2.17 on 2026-08-19 17:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imports', '0003_stagedsalesrow_existing_line_stagedsalesrow_sku_and_more'),
        ('master_data', '0002_alter_product_code_skuvaluehistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('Shopee', 'Shopee'), ('Tiktok', 'TikTok')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('parser_version', models.CharField(default='traffic-v1', max_length=30)),
                ('status', models.CharField(choices=[('PARSING', 'Parsing'), ('READY', 'Ready for approval'), ('BLOCKED', 'Blocked'), ('COMMITTED', 'Committed')], default='PARSING', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('ready_rows', models.PositiveIntegerField(default=0)),
                ('blocking_issue_count', models.PositiveIntegerField(default=0)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('quality_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('raw_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traffic_batches', to='imports.rawfile')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StagedTrafficRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.PositiveIntegerField()),
                ('marketplace_product_code', models.CharField(max_length=160)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('views', models.PositiveBigIntegerField(default=0)),
                ('clicks', models.PositiveBigIntegerField(default=0)),
                ('visitors', models.PositiveBigIntegerField(default=0)),
                ('selected_source_data', models.JSONField(default=dict)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.product')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staged_rows', to='traffic.trafficimportbatch')),
            ],
            options={
                'ordering': ('row_number',),
            },
        ),
        migrations.CreateModel(
            name='TrafficImportIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('ERROR', 'Error'), ('WARNING', 'Warning')], max_length=10)),
                ('code', models.CharField(max_length=80)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField()),
                ('is_blocking', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='traffic.trafficimportbatch')),
                ('staged_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='traffic.stagedtrafficrow')),
            ],
            options={
                'ordering': ('-is_blocking', 'staged_row__row_number', 'code'),
            },
        ),
        migrations.CreateModel(
            name='TrafficPeriodState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('Shopee', 'Shopee'), ('Tiktok', 'TikTok')], max_length=20)),
                ('month', models.DateField()),
                ('is_complete', models.BooleanField(default=False)),
                ('last_successful_import_at', models.DateTimeField(blank=True, null=True)),
                ('last_data_end', models.DateField(blank=True, null=True)),
                ('reopen_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('month', 'source'),
                'constraints': [models.UniqueConstraint(fields=('source', 'month'), name='traffic_unique_source_month_state')],
            },
        ),
        migrations.CreateModel(
            name='TrafficProductMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('Shopee', 'Shopee'), ('Tiktok', 'TikTok')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('marketplace_product_code_snapshot', models.CharField(max_length=160)),
                ('product_name_snapshot', models.CharField(blank=True, max_length=255)),
                ('views', models.PositiveBigIntegerField(default=0)),
                ('clicks', models.PositiveBigIntegerField(default=0)),
                ('visitors', models.PositiveBigIntegerField(default=0)),
                ('committed_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traffic_metrics', to='master_data.product')),
                ('source_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='committed_metrics', to='traffic.trafficimportbatch')),
            ],
            options={
                'ordering': ('period_start', 'source', 'product__name'),
            },
        ),
        migrations.AddConstraint(
            model_name='stagedtrafficrow',
            constraint=models.UniqueConstraint(fields=('batch', 'row_number'), name='traffic_unique_batch_row'),
        ),
        migrations.AddConstraint(
            model_name='trafficproductmetric',
            constraint=models.UniqueConstraint(fields=('source', 'period_start', 'product'), name='traffic_unique_period_product'),
        ),
    ]
