# Generated by Django 5.2.17 on 2026-08-19 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_marketplaceskumapping'),
        ('traffic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trafficproductmetric',
            name='traffic_unique_period_product',
        ),
        migrations.AddField(
            model_name='trafficproductmetric',
            name='category_snapshot',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='trafficproductmetric',
            name='is_historical_migration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trafficproductmetric',
            name='subcategory_snapshot',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='trafficproductmetric',
            name='traffic_product_key',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='trafficproductmetric',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traffic_metrics', to='master_data.product'),
        ),
        migrations.AddConstraint(
            model_name='trafficproductmetric',
            constraint=models.UniqueConstraint(fields=('source', 'period_start', 'traffic_product_key'), name='traffic_unique_period_product_key'),
        ),
    ]
