# Generated by Django 5.2.17 on 2026-10-01 09:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0002_remove_trafficproductmetric_traffic_unique_period_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreTrafficMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('Shopee', 'Shopee'), ('Tiktok', 'TikTok')], max_length=20)),
                ('traffic_date', models.DateField(db_index=True)),
                ('visitors', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_traffic_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-traffic_date', 'source'),
                'constraints': [models.UniqueConstraint(fields=('source', 'traffic_date'), name='traffic_unique_daily_store_source')],
            },
        ),
    ]
