# Generated by Django 5.2.17 on 2026-08-19 17:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0002_alter_product_code_skuvaluehistory'),
        ('merchandising', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PPICRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('need_month', models.DateField()),
                ('approved_qty', models.DecimalField(decimal_places=4, max_digits=18)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('incoming_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ppic_requirements', to='merchandising.incomingplan')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ppic_requirements', to='master_data.sku')),
            ],
            options={
                'ordering': ('need_month', 'sku__sku'),
            },
        ),
        migrations.CreateModel(
            name='PPICRequirementRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField()),
                ('previous_qty', models.DecimalField(decimal_places=4, max_digits=18)),
                ('approved_qty', models.DecimalField(decimal_places=4, max_digits=18)),
                ('reason', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='purchasing.ppicrequirement')),
            ],
            options={
                'ordering': ('requirement', 'revision'),
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('po_number', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('sequence', models.PositiveIntegerField(blank=True, null=True)),
                ('need_month', models.DateField()),
                ('source', models.CharField(choices=[('INCOMING_PLAN', 'Approved Incoming Plan'), ('MANUAL_NEW_PRODUCT', 'Manual – New Product')], default='INCOMING_PLAN', max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('RELEASED', 'Released'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('close_date', models.DateField(blank=True, null=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='released_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='master_data.supplier')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordered_qty', models.DecimalField(decimal_places=4, max_digits=18)),
                ('cogs_snapshot', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='purchasing.purchaseorder')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_lines', to='purchasing.ppicrequirement')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_lines', to='master_data.sku')),
            ],
            options={
                'ordering': ('po', 'sku__sku'),
            },
        ),
        migrations.AddConstraint(
            model_name='ppicrequirement',
            constraint=models.UniqueConstraint(fields=('need_month', 'sku'), name='purchasing_unique_need_month_sku'),
        ),
        migrations.AddConstraint(
            model_name='ppicrequirement',
            constraint=models.CheckConstraint(condition=models.Q(('approved_qty__gte', 0)), name='purchasing_requirement_qty_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='ppicrequirementrevision',
            constraint=models.UniqueConstraint(fields=('requirement', 'revision'), name='purchasing_unique_requirement_revision'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(condition=models.Q(('sequence__isnull', False)), fields=('need_month', 'sequence'), name='purchasing_unique_month_sequence'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.UniqueConstraint(fields=('po', 'sku'), name='purchasing_unique_po_sku'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('ordered_qty__gt', 0)), name='purchasing_po_line_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('cogs_snapshot__gte', 0), ('cogs_snapshot__isnull', True), _connector='OR'), name='purchasing_po_cogs_nonnegative'),
        ),
    ]
