# Generated by Django 5.2.17 on 2026-08-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_marketplaceskumapping'),
        ('purchasing', '0003_purchaseorder_required_arrival'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='migration_cutoff_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='migration_evidence_reference',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='qc_passed_before_cutover_qty',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='received_before_cutover_qty',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='source',
            field=models.CharField(choices=[('INCOMING_PLAN', 'Approved Incoming Plan'), ('MANUAL_NEW_PRODUCT', 'Manual – New Product'), ('LEGACY_WIP', 'PO WIP · outstanding per 31 July 2026')], default='INCOMING_PLAN', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('received_before_cutover_qty__gte', 0)), name='purchasing_legacy_received_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('qc_passed_before_cutover_qty__gte', 0)), name='purchasing_legacy_qc_nonnegative'),
        ),
    ]
