# Generated by Django 5.2.17 on 2026-08-19 16:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0002_alter_product_code_skuvaluehistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('Shopee', 'Shopee'), ('Tiktok', 'TikTok'), ('Other', 'Other')], max_length=20)),
                ('order_number', models.CharField(max_length=160)),
                ('order_datetime', models.DateTimeField()),
                ('order_date', models.DateField()),
                ('current_status', models.CharField(max_length=180)),
                ('source_status', models.CharField(max_length=255)),
                ('is_final', models.BooleanField(default=False)),
                ('is_pure_cancelled', models.BooleanField(default=False)),
                ('first_seen_batch_id', models.UUIDField()),
                ('latest_batch_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-order_datetime', 'source', 'order_number'),
                'indexes': [models.Index(fields=['source', 'current_status'], name='sales_sales_source_b0673c_idx'), models.Index(fields=['order_date', 'source'], name='sales_sales_order_d_57e31c_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'order_number'), name='sales_unique_source_order')],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('net_unit_price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('retail_price_snapshot', models.DecimalField(decimal_places=2, max_digits=18)),
                ('sales_cogs_snapshot', models.DecimalField(decimal_places=4, max_digits=18)),
                ('total_gross_sales', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_net_sales', models.DecimalField(decimal_places=4, max_digits=20)),
                ('total_cogs', models.DecimalField(decimal_places=4, max_digits=20)),
                ('gpm', models.DecimalField(decimal_places=4, max_digits=20)),
                ('gpm_rate', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('is_counted', models.BooleanField(default=True)),
                ('committed_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='sales.salesorder')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_lines', to='master_data.sku')),
            ],
            options={
                'ordering': ('order__order_datetime', 'order__order_number', 'sku__sku'),
                'constraints': [models.UniqueConstraint(fields=('order', 'sku'), name='sales_unique_order_sku_line'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='sales_line_quantity_positive'), models.CheckConstraint(condition=models.Q(('net_unit_price__gte', 0)), name='sales_line_net_price_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='SalesStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(blank=True, max_length=180)),
                ('normalized_status', models.CharField(max_length=180)),
                ('source_status', models.CharField(max_length=255)),
                ('observed_at', models.DateTimeField(auto_now_add=True)),
                ('import_batch_id', models.UUIDField()),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_status_changes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='sales.salesorder')),
            ],
            options={
                'ordering': ('-observed_at',),
                'indexes': [models.Index(fields=['order', 'observed_at'], name='sales_sales_order_i_b77944_idx')],
            },
        ),
    ]
