# Generated by Django 5.2.17 on 2026-08-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='shipped_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
