# Generated by Django 5.2.17 on 2026-08-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_salesorder_shipped_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='source_label',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
    ]
