# Generated by Django 5.2.17 on 2026-08-19 17:33

from django.db import migrations, models


def populate_source_label(apps, schema_editor):
    SalesOrder = apps.get_model("sales", "SalesOrder")
    for order in SalesOrder.objects.filter(source_label="").iterator():
        order.source_label = order.source
        order.save(update_fields=["source_label"])


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_salesorder_source_label'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='salesorder',
            name='sales_unique_source_order',
        ),
        migrations.RunPython(populate_source_label, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.UniqueConstraint(fields=('source_label', 'order_number'), name='sales_unique_source_label_order'),
        ),
    ]
