# Generated by Django 5.2.17 on 2026-08-19 19:10

import django.db.models.deletion
from django.db import migrations, models


def snapshot_existing_lines(apps, schema_editor):
    SalesOrderLine = apps.get_model("sales", "SalesOrderLine")
    for line in SalesOrderLine.objects.select_related(
        "sku__product_variant__product__status",
        "sku__product_variant__product__category",
        "sku__product_variant__product__subcategory",
    ).iterator(chunk_size=1000):
        if not line.sku_id:
            continue
        product = line.sku.product_variant.product
        line.sku_code_snapshot = line.sku.sku
        line.product_status_snapshot = product.status.name
        line.category_snapshot = product.category.name
        line.subcategory_snapshot = product.subcategory.name if product.subcategory_id else ""
        line.product_name_snapshot = product.name
        line.variant_name_snapshot = line.sku.size
        line.save(update_fields=[
            "sku_code_snapshot",
            "product_status_snapshot",
            "category_snapshot",
            "subcategory_snapshot",
            "product_name_snapshot",
            "variant_name_snapshot",
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_marketplaceskumapping'),
        ('sales', '0004_remove_salesorder_sales_unique_source_order_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='salesorderline',
            name='sales_unique_order_sku_line',
        ),
        migrations.AddField(
            model_name='salesorder',
            name='affects_inventory',
            field=models.BooleanField(default=True, help_text='False untuk histori pra-cutover yang sudah terserap dalam FIFO Opening.'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='import_origin',
            field=models.CharField(choices=[('OPERATIONAL', 'Operational import'), ('HISTORICAL', 'Historical migration'), ('MANUAL', 'Manual entry')], default='OPERATIONAL', max_length=20),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='category_snapshot',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='product_name_snapshot',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='product_status_snapshot',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='sku_code_snapshot',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='subcategory_snapshot',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='variant_name_snapshot',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='gpm',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='retail_price_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='sales_cogs_snapshot',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_lines', to='master_data.sku'),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='total_cogs',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='total_gross_sales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.RunPython(snapshot_existing_lines, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.UniqueConstraint(fields=('order', 'sku_code_snapshot'), name='sales_unique_order_sku_snapshot_line'),
        ),
    ]
