# Generated by Django 5.2.17 on 2026-09-11 11:53

from django.db import migrations, models


def copy_order_status_to_lines(apps, schema_editor):
    SalesOrderLine = apps.get_model("sales", "SalesOrderLine")
    pending = []
    for line in SalesOrderLine.objects.select_related("order").iterator(chunk_size=2000):
        line.current_status = line.order.current_status
        line.source_status = line.order.source_status
        line.is_final = line.order.is_final
        line.is_pure_cancelled = line.order.is_pure_cancelled
        pending.append(line)
        if len(pending) == 2000:
            SalesOrderLine.objects.bulk_update(
                pending,
                ["current_status", "source_status", "is_final", "is_pure_cancelled"],
                batch_size=2000,
            )
            pending = []
    if pending:
        SalesOrderLine.objects.bulk_update(
            pending,
            ["current_status", "source_status", "is_final", "is_pure_cancelled"],
            batch_size=2000,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_unique_month_product_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderline',
            name='current_status',
            field=models.CharField(blank=True, db_index=True, max_length=180),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='is_pure_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='source_status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(copy_order_status_to_lines, migrations.RunPython.noop),
    ]
