# Generated by Django 5.2.17 on 2026-08-23 05:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def create_existing_production_workflows(apps, schema_editor):
    PurchaseOrder = apps.get_model('purchasing', 'PurchaseOrder')
    ProductionOrder = apps.get_model('production', 'ProductionOrder')
    ProductionStage = apps.get_model('production', 'ProductionStage')
    stage_codes = ('MATERIAL_PURCHASE', 'MATERIAL_VENDOR', 'CUT', 'MAKE', 'TRIM')
    for po in PurchaseOrder.objects.filter(status='RELEASED').iterator():
        production_order = ProductionOrder.objects.create(po=po)
        ProductionStage.objects.bulk_create([
            ProductionStage(production_order=production_order, stage=stage_code)
            for stage_code in stage_codes
        ])


def remove_existing_production_workflows(apps, schema_editor):
    ProductionStage = apps.get_model('production', 'ProductionStage')
    ProductionOrder = apps.get_model('production', 'ProductionOrder')
    ProductionStage.objects.all().delete()
    ProductionOrder.objects.all().delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchasing', '0007_po_number_uses_issue_month'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('po', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='production_order', to='purchasing.purchaseorder')),
            ],
            options={
                'ordering': ('po__required_arrival', 'po__po_number'),
            },
        ),
        migrations.CreateModel(
            name='ProductionActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=80)),
                ('stage', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField()),
                ('before_values', models.JSONField(blank=True, default=dict)),
                ('after_values', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_activities', to=settings.AUTH_USER_MODEL)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='production.productionorder')),
            ],
            options={
                'ordering': ('-occurred_at',),
                'indexes': [models.Index(fields=['production_order', 'occurred_at'], name='production__product_ffd8b0_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductionStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('MATERIAL_PURCHASE', 'Pembelian Material'), ('MATERIAL_VENDOR', 'Material Masuk Vendor'), ('CUT', 'Cut · Potong'), ('MAKE', 'Make · Jahit'), ('TRIM', 'Trim · Finishing')], max_length=30)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Belum dimulai'), ('IN_PROGRESS', 'Sedang berjalan'), ('BLOCKED', 'Terkendala'), ('COMPLETE', 'Selesai')], default='NOT_STARTED', max_length=20)),
                ('target_start_date', models.DateField(blank=True, null=True)),
                ('target_end_date', models.DateField(blank=True, null=True)),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='production.productionorder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_production_stages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('production_order', 'stage'),
                'constraints': [models.UniqueConstraint(fields=('production_order', 'stage'), name='production_unique_order_stage'), models.CheckConstraint(condition=models.Q(('progress_percent__gte', 0), ('progress_percent__lte', 100)), name='production_stage_progress_0_100')],
            },
        ),
        migrations.CreateModel(
            name='ProductionTrial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'Trial sedang dibuat'), ('WAITING_APPROVAL', 'Menunggu approval'), ('APPROVED', 'Approved'), ('REVISION_REQUIRED', 'Perlu revisi')], default='IN_PROGRESS', max_length=30)),
                ('trial_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('decision_notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_production_trials', to=settings.AUTH_USER_MODEL)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trials', to='production.productionorder')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='started_production_trials', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_production_trials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('production_order', '-revision'),
                'constraints': [models.UniqueConstraint(fields=('production_order', 'revision'), name='production_unique_trial_revision')],
            },
        ),
        migrations.RunPython(create_existing_production_workflows, remove_existing_production_workflows),
    ]
