# Generated by Django 5.2.17 on 2026-08-19 16:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0002_alter_product_code_skuvaluehistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectionScenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('start_month', models.DateField()),
                ('end_month', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('SUPERSEDED', 'Superseded')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_projection_scenarios', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_projection_scenarios', to=settings.AUTH_USER_MODEL)),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_scenarios', to='merchandising.projectionscenario')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProjectionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_month', models.DateField()),
                ('scope_type', models.CharField(choices=[('PRODUCT_STATUS', 'Product Status'), ('CATEGORY', 'Category'), ('PRODUCT', 'Product')], max_length=30)),
                ('method', models.CharField(choices=[('INCREASE_PERCENT', 'Increase by %'), ('DECREASE_PERCENT', 'Decrease by %'), ('TARGET_STOCK_RATIO', 'Target Stock Ratio')], max_length=30)),
                ('parameter', models.DecimalField(decimal_places=4, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projection_rules', to='master_data.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projection_rules', to='master_data.product')),
                ('product_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projection_rules', to='master_data.productstatus')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='merchandising.projectionscenario')),
            ],
            options={
                'ordering': ('target_month', 'scope_type', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='SalesProjection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.DateField()),
                ('baseline_month', models.DateField(blank=True, null=True)),
                ('baseline_qty', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('beginning_qty', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('system_recommendation', models.DecimalField(decimal_places=4, max_digits=18)),
                ('adit_adjustment', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('final_approved_qty', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('approval_status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20)),
                ('explanation', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('applied_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projection_results', to='merchandising.projectionrule')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_sales_projections', to=settings.AUTH_USER_MODEL)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projections', to='merchandising.projectionscenario')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_projections', to='master_data.sku')),
            ],
            options={
                'ordering': ('month', 'sku__sku'),
            },
        ),
        migrations.CreateModel(
            name='IncomingPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.DateField()),
                ('prior_ending_qty', models.DecimalField(decimal_places=4, max_digits=18)),
                ('minimum_incoming', models.DecimalField(decimal_places=4, max_digits=18)),
                ('target_stock_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('recommended_incoming', models.DecimalField(decimal_places=4, max_digits=18)),
                ('adit_adjustment', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('final_approved_incoming', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('approval_status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_incoming_plans', to=settings.AUTH_USER_MODEL)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_plans', to='master_data.sku')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_plans', to='merchandising.projectionscenario')),
                ('sales_projection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_plans', to='merchandising.salesprojection')),
            ],
            options={
                'ordering': ('month', 'sku__sku'),
            },
        ),
        migrations.AddIndex(
            model_name='projectionrule',
            index=models.Index(fields=['scenario', 'target_month', 'scope_type'], name='merchandisi_scenari_a89b9c_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesprojection',
            constraint=models.UniqueConstraint(fields=('scenario', 'month', 'sku'), name='merch_unique_scenario_month_sku_projection'),
        ),
        migrations.AddConstraint(
            model_name='salesprojection',
            constraint=models.CheckConstraint(condition=models.Q(('system_recommendation__gte', 0)), name='merch_projection_recommendation_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='incomingplan',
            constraint=models.UniqueConstraint(fields=('scenario', 'month', 'sku'), name='merch_unique_scenario_month_sku_incoming'),
        ),
        migrations.AddConstraint(
            model_name='incomingplan',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_incoming__gte', 0)), name='merch_minimum_incoming_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='incomingplan',
            constraint=models.CheckConstraint(condition=models.Q(('recommended_incoming__gte', 0)), name='merch_recommended_incoming_nonnegative'),
        ),
    ]
