# Generated by Django 5.2.17 on 2026-08-21 08:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_marketplaceskumapping'),
        ('merchandising', '0002_merchandising_snapshot'),
        ('purchasing', '0003_purchaseorder_required_arrival'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingMonthClose',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.DateField(unique=True)),
                ('cutoff_date', models.DateField()),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('evidence_reference', models.CharField(max_length=240)),
                ('notes', models.TextField(blank=True)),
                ('closed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='closed_incoming_months', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-month',),
            },
        ),
        migrations.CreateModel(
            name='IncomingCarryover',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_month', models.DateField()),
                ('carryover_qty', models.DecimalField(decimal_places=4, max_digits=18)),
                ('reason', models.CharField(default='Outstanding PO at incoming month close', max_length=240)),
                ('po_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_carryovers', to='purchasing.purchaseorderline')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_carryovers', to='master_data.sku')),
                ('source_close', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carryovers', to='merchandising.incomingmonthclose')),
            ],
            options={
                'ordering': ('target_month', 'sku__sku', 'po_line__po__required_arrival'),
                'constraints': [models.UniqueConstraint(fields=('source_close', 'po_line'), name='merch_unique_close_po_line_carryover'), models.CheckConstraint(condition=models.Q(('carryover_qty__gt', 0)), name='merch_carryover_qty_positive')],
            },
        ),
        migrations.CreateModel(
            name='IncomingMonthlyActual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('projected_qty', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('actual_qty', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('actual_cogs', models.DecimalField(decimal_places=4, default=0, max_digits=22)),
                ('actual_gross', models.DecimalField(decimal_places=4, default=0, max_digits=22)),
                ('variance_qty', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('month_close', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actual_rows', to='merchandising.incomingmonthclose')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_monthly_actuals', to='master_data.sku')),
            ],
            options={
                'ordering': ('month_close__month', 'sku__sku'),
                'constraints': [models.UniqueConstraint(fields=('month_close', 'sku'), name='merch_unique_close_sku_actual')],
            },
        ),
    ]
