# Generated by Django 5.2.17 on 2026-08-31 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandising', '0007_month_close_cost_actuals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectionscenario',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('REVISION_DRAFT', 'Revision Draft'), ('APPROVED', 'Approved'), ('SUPERSEDED', 'Superseded')], default='DRAFT', max_length=20),
        ),
    ]
