# Generated by Django 5.2.17 on 2026-08-29 08:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0005_reject_warehouse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('approval_date', models.DateField()),
                ('sample_date', models.DateField()),
                ('creative_date', models.DateField()),
                ('prelaunch_date', models.DateField()),
                ('launch_date', models.DateField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('actual_spent', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-launch_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='CampaignCreative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('TIKTOK', 'TikTok')], max_length=20)),
                ('post_url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatives', to='dashboard.campaign')),
            ],
            options={
                'ordering': ('platform', 'created_at'),
                'constraints': [models.UniqueConstraint(fields=('campaign', 'post_url'), name='dashboard_campaign_creative_unique')],
            },
        ),
        migrations.CreateModel(
            name='CampaignProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_qty', models.PositiveIntegerField()),
                ('retail_price_snapshot', models.DecimalField(decimal_places=2, max_digits=18)),
                ('target_gross_sales', models.DecimalField(decimal_places=2, max_digits=20)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='dashboard.campaign')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.product')),
            ],
            options={
                'ordering': ('product__name',),
                'constraints': [models.UniqueConstraint(fields=('campaign', 'product'), name='dashboard_campaign_product_unique')],
            },
        ),
    ]
