# Generated by Django 5.2.17 on 2026-08-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_plan_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
