# Generated by Django 5.2.17 on 2026-08-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_campaignexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='cover',
            field=models.FileField(blank=True, upload_to='campaign_covers/'),
        ),
    ]
