# Generated by Django 5.2.17 on 2026-08-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_campaign_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='creative_asset_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
