# Generated by Django 5.2.17 on 2026-09-01 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_social_daily_metrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPeriodMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('TIKTOK', 'TikTok')], max_length=20)),
                ('account', models.CharField(max_length=100)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('reach', models.PositiveBigIntegerField(blank=True, null=True)),
                ('impressions', models.PositiveBigIntegerField(blank=True, null=True)),
                ('total_engagement', models.PositiveBigIntegerField(blank=True, null=True)),
                ('accounts_engaged', models.PositiveBigIntegerField(blank=True, null=True)),
                ('profile_visits', models.PositiveBigIntegerField(blank=True, null=True)),
                ('website_clicks', models.PositiveBigIntegerField(blank=True, null=True)),
                ('likes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('comments', models.PositiveBigIntegerField(blank=True, null=True)),
                ('shares', models.PositiveBigIntegerField(blank=True, null=True)),
                ('new_followers', models.PositiveBigIntegerField(blank=True, null=True)),
                ('lost_followers', models.PositiveBigIntegerField(blank=True, null=True)),
                ('synced_at', models.DateTimeField()),
            ],
            options={
                'ordering': ('platform', 'account', 'date_from', 'date_to'),
                'constraints': [models.UniqueConstraint(fields=('platform', 'account', 'date_from', 'date_to'), name='dashboard_social_period_platform_account_dates_unique')],
            },
        ),
    ]
