# Generated by Django 5.2.17 on 2026-08-19 16:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0002_alter_product_code_skuvaluehistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RawFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dataset_type', models.CharField(choices=[('MASTER_PRODUCT', 'Master Product')], max_length=40)),
                ('original_filename', models.CharField(max_length=255)),
                ('storage_path', models.CharField(max_length=500, unique=True)),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('byte_size', models.PositiveBigIntegerField()),
                ('detected_format', models.CharField(max_length=12)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_raw_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-uploaded_at',),
            },
        ),
        migrations.CreateModel(
            name='MasterImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parser_version', models.CharField(default='master-v1', max_length=30)),
                ('status', models.CharField(choices=[('PARSING', 'Parsing'), ('READY', 'Ready for approval'), ('BLOCKED', 'Blocked'), ('COMMITTED', 'Committed'), ('REJECTED', 'Rejected')], default='PARSING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('previewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('new_rows', models.PositiveIntegerField(default=0)),
                ('changed_rows', models.PositiveIntegerField(default=0)),
                ('unchanged_rows', models.PositiveIntegerField(default=0)),
                ('blocking_issue_count', models.PositiveIntegerField(default=0)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('quality_summary', models.JSONField(blank=True, default=dict)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_master_imports', to=settings.AUTH_USER_MODEL)),
                ('raw_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='master_batches', to='imports.rawfile')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StagedMasterRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.PositiveIntegerField()),
                ('source', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=100)),
                ('parent_sku', models.CharField(blank=True, max_length=100)),
                ('article', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('variant', models.CharField(blank=True, max_length=150)),
                ('sub_variant', models.CharField(blank=True, max_length=100)),
                ('product_status', models.CharField(max_length=100)),
                ('cogs', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('retail_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('shopee_code', models.CharField(blank=True, max_length=160)),
                ('tiktok_code', models.CharField(blank=True, max_length=160)),
                ('proposed_action', models.CharField(choices=[('NEW', 'New'), ('UPDATE', 'Update'), ('UNCHANGED', 'Unchanged'), ('BLOCKED', 'Blocked')], default='NEW', max_length=20)),
                ('original_data', models.JSONField(default=dict)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staged_rows', to='imports.masterimportbatch')),
                ('existing_sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staged_master_updates', to='master_data.sku')),
            ],
            options={
                'ordering': ('row_number',),
            },
        ),
        migrations.CreateModel(
            name='ImportValidationIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('ERROR', 'Error'), ('WARNING', 'Warning')], max_length=10)),
                ('code', models.CharField(max_length=80)),
                ('field_name', models.CharField(blank=True, max_length=80)),
                ('message', models.TextField()),
                ('is_blocking', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='imports.masterimportbatch')),
                ('staged_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='imports.stagedmasterrow')),
            ],
            options={
                'ordering': ('-is_blocking', 'staged_row__row_number', 'code'),
            },
        ),
        migrations.AddConstraint(
            model_name='rawfile',
            constraint=models.UniqueConstraint(fields=('dataset_type', 'checksum_sha256'), name='imports_unique_dataset_checksum'),
        ),
        migrations.AddIndex(
            model_name='stagedmasterrow',
            index=models.Index(fields=['batch', 'sku'], name='imports_sta_batch_i_56e26f_idx'),
        ),
        migrations.AddConstraint(
            model_name='stagedmasterrow',
            constraint=models.UniqueConstraint(fields=('batch', 'row_number'), name='imports_unique_master_row_number'),
        ),
        migrations.AddIndex(
            model_name='importvalidationissue',
            index=models.Index(fields=['batch', 'is_blocking'], name='imports_imp_batch_i_67a8e8_idx'),
        ),
        migrations.AddIndex(
            model_name='importvalidationissue',
            index=models.Index(fields=['batch', 'severity'], name='imports_imp_batch_i_71b474_idx'),
        ),
    ]
