# Generated by Django 5.2.17 on 2026-08-19 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_alter_rawfile_dataset_type_salesimportbatch_and_more'),
        ('master_data', '0002_alter_product_code_skuvaluehistory'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagedsalesrow',
            name='existing_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staged_updates', to='sales.salesorderline'),
        ),
        migrations.AddField(
            model_name='stagedsalesrow',
            name='sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staged_sales_rows', to='master_data.sku'),
        ),
        migrations.AddField(
            model_name='salesimportissue',
            name='staged_row',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='imports.stagedsalesrow'),
        ),
        migrations.AddIndex(
            model_name='stagedsalesrow',
            index=models.Index(fields=['batch', 'order_number', 'sku_text'], name='imports_sta_batch_i_3ff947_idx'),
        ),
        migrations.AddIndex(
            model_name='stagedsalesrow',
            index=models.Index(fields=['batch', 'proposed_action'], name='imports_sta_batch_i_f7a53f_idx'),
        ),
        migrations.AddConstraint(
            model_name='stagedsalesrow',
            constraint=models.UniqueConstraint(fields=('batch', 'row_number'), name='imports_unique_sales_row_number'),
        ),
        migrations.AddIndex(
            model_name='salesimportissue',
            index=models.Index(fields=['batch', 'is_blocking'], name='imports_sal_batch_i_c7d975_idx'),
        ),
        migrations.AddIndex(
            model_name='salesimportissue',
            index=models.Index(fields=['batch', 'code'], name='imports_sal_batch_i_c512f9_idx'),
        ),
    ]
