# Generated by Django 5.2.17 on 2026-08-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0004_alter_rawfile_dataset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesimportbatch',
            name='out_of_scope_rows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stagedsalesrow',
            name='proposed_action',
            field=models.CharField(choices=[('NEW', 'New'), ('STATUS_UPDATE', 'Status update'), ('UNCHANGED', 'Unchanged'), ('PURE_CANCEL', 'Pure cancellation'), ('OUT_OF_SCOPE', 'Before cutover'), ('BLOCKED', 'Blocked')], default='NEW', max_length=20),
        ),
    ]
