# Generated by Django 5.2.17 on 2026-08-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0005_salesimportbatch_out_of_scope_rows_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesimportbatch',
            name='mode',
            field=models.CharField(choices=[('OPERATIONAL', 'Operational'), ('HISTORICAL', 'Historical migration')], default='OPERATIONAL', max_length=20),
        ),
        migrations.AddField(
            model_name='stagedsalesrow',
            name='category_snapshot',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='stagedsalesrow',
            name='gpm_snapshot',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='stagedsalesrow',
            name='product_name_snapshot',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='stagedsalesrow',
            name='product_status_snapshot',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='stagedsalesrow',
            name='source_group',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='stagedsalesrow',
            name='source_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='stagedsalesrow',
            name='subcategory_snapshot',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='stagedsalesrow',
            name='total_cogs_snapshot',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='stagedsalesrow',
            name='total_gross_sales_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='stagedsalesrow',
            name='total_net_sales_snapshot',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='stagedsalesrow',
            name='variant_name_snapshot',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='rawfile',
            name='dataset_type',
            field=models.CharField(choices=[('MASTER_PRODUCT', 'Master Product'), ('FIFO_OPENING', 'FIFO Opening'), ('SALES_SHOPEE', 'Sales Shopee'), ('SALES_TIKTOK', 'Sales TikTok'), ('SALES_HISTORICAL', 'Sales Historical'), ('TRAFFIC_SHOPEE', 'Traffic Shopee'), ('TRAFFIC_TIKTOK', 'Traffic TikTok')], max_length=40),
        ),
        migrations.AlterField(
            model_name='salesimportbatch',
            name='source',
            field=models.CharField(choices=[('Shopee', 'Shopee'), ('Tiktok', 'TikTok'), ('Canonical', 'Canonical Vobia Sales')], max_length=20),
        ),
    ]
